//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guester.Resources
{
    using System;
    using System.Resources;


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guester.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }



        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить комментарий к чеку.
        /// </summary>
        internal static string AddCommentToReceipt {
            get {
                return ResourceManager.GetString("AddCommentToReceipt", resourceCulture);
            }
        }

        internal static string SelectOrderType
        {
            get
            {
                return ResourceManager.GetString("SelectOrderType", resourceCulture);
            }
        }

        internal static string Takeaway
        {
            get
            {
                return ResourceManager.GetString("Takeaway", resourceCulture);
            }
        }


        internal static string CurrentHall
        {
            get
            {
                return ResourceManager.GetString("CurrentHall", resourceCulture);
            }
        }

        internal static string IPAddress
        {
            get
            {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }

        internal static string LogOutOfApp
        {
            get
            {
                return ResourceManager.GetString("LogOutOfApp", resourceCulture);
            }
        }

        internal static string InTheEstablishment
        {
            get
            {
                return ResourceManager.GetString("InTheEstablishment", resourceCulture);
            }
        }

        internal static string DeviceName
        {
            get
            {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }

        internal static string SelectType
        {
            get
            {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }

        internal static string ClearCache
        {
            get
            {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }

        internal static string LoginKKM
        {
            get
            {
                return ResourceManager.GetString("LoginKKM", resourceCulture);
            }
        }

        internal static string PasswordKKM
        {
            get
            {
                return ResourceManager.GetString("PasswordKKM", resourceCulture);
            }
        }

        internal static string SelectATable
        {
            get
            {
                return ResourceManager.GetString("SelectATable", resourceCulture);
            }
        }

        internal static string DisableFixedCheck
        {
            get
            {
                return ResourceManager.GetString("DisableFixedCheck", resourceCulture);
            }
        }

        internal static string Printer
        {
            get
            {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }

        internal static string KKM
        {
            get
            {
                return ResourceManager.GetString("KKM", resourceCulture);
            }
        }

        internal static string Scanner
        {
            get
            {
                return ResourceManager.GetString("Scanner", resourceCulture);
            }
        }


        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибавил количество продукта.
        /// </summary>
        internal static string AddedProductQuantity {
            get {
                return ResourceManager.GetString("AddedProductQuantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОБАВИТЬ ГОСТЯ.
        /// </summary>
        internal static string AddGuest {
            get {
                return ResourceManager.GetString("AddGuest", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Все заказы.
        /// </summary>
        internal static string AllOrders {
            get {
                return ResourceManager.GetString("AllOrders", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Все товары.
        /// </summary>
        internal static string AllProducts {
            get {
                return ResourceManager.GetString("AllProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Все чеки.
        /// </summary>
        internal static string AllReceipts {
            get {
                return ResourceManager.GetString("AllReceipts", resourceCulture);
            }
        } internal static string Confirm
        {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        } internal static string ConfirmLabel
        {
            get {
                return ResourceManager.GetString("ConfirmLabel", resourceCulture);
            }
        }
        internal static string Checks
        {
            get {
                return ResourceManager.GetString("Checks", resourceCulture);
            }
        }


        internal static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Все смены.
        /// </summary>
        internal static string AllShifts {
            get {
                return ResourceManager.GetString("AllShifts", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка удалить последнего гостя.
        /// </summary>
        internal static string AttempDeleteLastGuest {
            get {
                return ResourceManager.GetString("AttempDeleteLastGuest", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на ВЫПЕЧКА.
        /// </summary>
        internal static string Bakery {
            get {
                return ResourceManager.GetString("Bakery", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Бар.
        /// </summary>
        internal static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Счёт закрыт.
        /// </summary>
        internal static string BillClosed {
            get {
                return ResourceManager.GetString("BillClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Бронирование.
        /// </summary>
        internal static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Булочки.
        /// </summary>
        internal static string Buns {
            get {
                return ResourceManager.GetString("Buns", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Банковской картой.
        /// </summary>
        internal static string ByBankCard {
            get {
                return ResourceManager.GetString("ByBankCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Торты.
        /// </summary>
        internal static string Cakes {
            get {
                return ResourceManager.GetString("Cakes", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        } internal static string AddToCheck
        {
            get {
                return ResourceManager.GetString("AddToCheck", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на отменил.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        internal static string PersonalInfo
        {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        } internal static string FLMClient
        {
            get {
                return ResourceManager.GetString("FLMClient", resourceCulture);
            }
        } internal static string EnterFlmClient
        {
            get {
                return ResourceManager.GetString("EnterFlmClient", resourceCulture);
            }
        } internal static string NumberPhone
        {
            get {
                return ResourceManager.GetString("NumberPhone", resourceCulture);
            }
        } internal static string ClientEmail
        {
            get {
                return ResourceManager.GetString("ClientEmail", resourceCulture);
            }
        } internal static string BirthDayDate
        {
            get {
                return ResourceManager.GetString("BirthDayDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить заказ.
        /// </summary>
        internal static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Капучино.
        /// </summary>
        internal static string Cappuccino {
            get {
                return ResourceManager.GetString("Cappuccino", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Наличными.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Кассовая смена.
        /// </summary>
        internal static string CashShift {
            get {
                return ResourceManager.GetString("CashShift", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Сертификатом.
        /// </summary>
        internal static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Сдача:.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиент.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть смену.
        /// </summary>
        internal static string CloseShift {
            get {
                return ResourceManager.GetString("CloseShift", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть без оплаты.
        /// </summary>
        internal static string CloseWithoutPayment {
            get {
                return ResourceManager.GetString("CloseWithoutPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на КОФЕ.
        /// </summary>
        internal static string Coffee {
            get {
                return ResourceManager.GetString("Coffee", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Кола.
        /// </summary>
        internal static string Cola {
            get {
                return ResourceManager.GetString("Cola", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать транзакцию.
        /// </summary>
        internal static string CreateTransaction {
            get {
                return ResourceManager.GetString("CreateTransaction", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Доставка.
        /// </summary>
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        internal static string Courer
        {
            get {
                return ResourceManager.GetString("Courer", resourceCulture);
            }
        } internal static string SelectedCourer
        {
            get {
                return ResourceManager.GetString("SelectedCourer", resourceCulture);
            }
        } internal static string DetailDelivery
        {
            get {
                return ResourceManager.GetString("DetailDelivery", resourceCulture);
            }
        } internal static string SubmisionTime
        {
            get {
                return ResourceManager.GetString("SubmisionTime", resourceCulture);
            }
        } internal static string Modifiers
        {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Время доставки.
        /// </summary>
        internal static string DeliveryTime {
            get {
                return ResourceManager.GetString("DeliveryTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Устройства.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Скидка.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на НАПИТКИ.
        /// </summary>
        internal static string Drinks {
            get {
                return ResourceManager.GetString("Drinks", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.
        /// </summary>
        internal static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлен продукт.
        /// </summary>
        internal static string AddProduct
        {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Смены сотрудников.
        /// </summary>
        internal static string EmplyeeShifts {
            get {
                return ResourceManager.GetString("EmplyeeShifts", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        internal static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Закончить смену.
        /// </summary>
        internal static string EndShift {
            get {
                return ResourceManager.GetString("EndShift", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский язык.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите текст.
        /// </summary>
        internal static string EnterText {
            get {
                return ResourceManager.GetString("EnterText", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Оборудование.
        /// </summary>
        internal static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при добавлении продукта.
        /// </summary>
        internal static string ErrorAddingProduct {
            get {
                return ResourceManager.GetString("ErrorAddingProduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Эспрессо.
        /// </summary>
        internal static string Espresso {
            get {
                return ResourceManager.GetString("Espresso", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Фанта.
        /// </summary>
        internal static string Fanta {
            get {
                return ResourceManager.GetString("Fanta", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Фискализация.
        /// </summary>
        internal static string Fiscalization {
            get {
                return ResourceManager.GetString("Fiscalization", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.
        /// </summary>
        internal static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.
        /// </summary>
        internal static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Функции.
        /// </summary>
        internal static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Гость.
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        internal static string FillAllField
        {
            get {
                return ResourceManager.GetString("FillAllField", resourceCulture);
            }
        }
        internal static string AllItems
        {
            get {
                return ResourceManager.GetString("AllItems", resourceCulture);
            }
        } internal static string PayedSertificateLabel
        {
            get {
                return ResourceManager.GetString("PayedSertificateLabel", resourceCulture);
            }
        }
        internal static string ClosedLabel
        {
            get {
                return ResourceManager.GetString("ClosedLabel", resourceCulture);
            }
        }

        internal static string Off
        {
            get
            {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }


        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлен гость.
        /// </summary>
        internal static string GuestAdded {
            get {
                return ResourceManager.GetString("GuestAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во гостей.
        /// </summary>
        internal static string GuestQuantity {
            get {
                return ResourceManager.GetString("GuestQuantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Карта зала.
        /// </summary>
        internal static string Hallmap {
            get {
                return ResourceManager.GetString("Hallmap", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Мороженое.
        /// </summary>
        internal static string IceCream {
            get {
                return ResourceManager.GetString("IceCream", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на В заведении.
        /// </summary>
        internal static string InEnvy {
            get {
                return ResourceManager.GetString("InEnvy", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на В ресторане.
        /// </summary>
        internal static string InRestaurant {
            get {
                return ResourceManager.GetString("InRestaurant", resourceCulture);
            }
        } internal static string WasCreateNewOrder
        {
            get {
                return ResourceManager.GetString("WasCreateNewOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый или неподходящий код.
        /// </summary>
        internal static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Инвентаризация.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на В пути.
        /// </summary>
        internal static string InWay {
            get {
                return ResourceManager.GetString("InWay", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на тг.
        /// </summary>
        internal static string KZT {
            get {
                return ResourceManager.GetString("KZT", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Латте.
        /// </summary>
        internal static string Latte {
            get {
                return ResourceManager.GetString("Latte", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Остатки на складе.
        /// </summary>
        internal static string LeftoversWarehouse {
            get {
                return ResourceManager.GetString("LeftoversWarehouse", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Смешанная оплата.
        /// </summary>
        internal static string MixedPayment {
            get {
                return ResourceManager.GetString("MixedPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Месяц.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Новые.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая бронь.
        /// </summary>
        internal static string NewBooking {
            get {
                return ResourceManager.GetString("NewBooking", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый заказ.
        /// </summary>
        internal static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        } internal static string NewLabel {
            get {
                return ResourceManager.GetString("NewLabel", resourceCulture);
            }
        } internal static string ReadyLabel
        {
            get {
                return ResourceManager.GetString("ReadyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 9.
        /// </summary>
        internal static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на №25.
        /// </summary>
        internal static string NumberTwentyFive {
            get {
                return ResourceManager.GetString("NumberTwentyFive", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Онлайн.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыт.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть  денежный ящик.
        /// </summary>
        internal static string OpenMoneyBox {
            get {
                return ResourceManager.GetString("OpenMoneyBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыт заказ №.
        /// </summary>
        internal static string OpenOrder {
            get {
                return ResourceManager.GetString("OpenOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменен.
        /// </summary>
        internal static string OrCancelled {
            get {
                return ResourceManager.GetString("OrCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрытый.
        /// </summary>
        internal static string OrClossed {
            get {
                return ResourceManager.GetString("OrClossed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказы.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        internal static string CardHall
        {
            get {
                return ResourceManager.GetString("CardHall", resourceCulture);
            }
        } internal static string Warehouse
        {
            get {
                return ResourceManager.GetString("Склад", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип заказа.
        /// </summary>
        internal static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ под №.
        /// </summary>
        internal static string OrderUnderNumber {
            get {
                return ResourceManager.GetString("OrderUnderNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ был закрыт.
        /// </summary>
        internal static string OrderWasClosed {
            get {
                return ResourceManager.GetString("OrderWasClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ был закрыт без оплаты.
        /// </summary>
        internal static string OrderWasClossedWithoutPayment {
            get {
                return ResourceManager.GetString("OrderWasClossedWithoutPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Другое.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на УЗБ.
        /// </summary>
        internal static string Oz {
            get {
                return ResourceManager.GetString("Oz", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплачено картой.
        /// </summary>
        internal static string PaidByCard {
            get {
                return ResourceManager.GetString("PaidByCard", resourceCulture);
            }
        }


        internal static string PaidLabel
        {
            get {
                return ResourceManager.GetString("PaidLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплачено наличными.
        /// </summary>
        internal static string PaidInCash {
            get {
                return ResourceManager.GetString("PaidInCash", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплатить.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        internal static string CountryLabel
        {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        internal static string City
        {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        internal static string EnterCountry
        {
            get {
                return ResourceManager.GetString("Введитестрану", resourceCulture);
            }
        }
        internal static string EnterCity
        {
            get {
                return ResourceManager.GetString("EnterCity", resourceCulture);
            }
        }
        internal static string EnterAddress
        {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        internal static string Commentary
        {
            get {
                return ResourceManager.GetString("Commentary", resourceCulture);
            }
        }
        internal static string NewClient
        {
            get {
                return ResourceManager.GetString("NewClient", resourceCulture);
            }
        }
        internal static string ClientGroup
        {
            get {
                return ResourceManager.GetString("ClientGroup", resourceCulture);
            }
        }
        internal static string AddNewCard
        {
            get {
                return ResourceManager.GetString("AddNewCard", resourceCulture);
            }
        } internal static string AddNewAddress
        {
            get {
                return ResourceManager.GetString("AddNewAddress", resourceCulture);
            }
        } internal static string Register
        {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        } internal static string AuthorizationDevice
        {
            get {
                return ResourceManager.GetString("AuthorizationDevice", resourceCulture);
            }
        } internal static string EnterLogin
        {
            get {
                return ResourceManager.GetString("EnterLogin", resourceCulture);
            }
        } internal static string EnterPswd
        {
            get {
                return ResourceManager.GetString("EnterPswd", resourceCulture);
            }
        } internal static string DeviceAuthLabel
        {
            get {
                return ResourceManager.GetString("DeviceAuthLabel", resourceCulture);
            }
        }
        internal static string SelectedClientGroup
        {
            get {
                return ResourceManager.GetString("SelectedClientGroup", resourceCulture);
            }
        } internal static string ClientCard
        {
            get {
                return ResourceManager.GetString("ClientCard", resourceCulture);
            }
        }
        internal static string Bonuses
        {
            get {
                return ResourceManager.GetString("Bonuses", resourceCulture);
            }
        }
        internal static string CardNumber
        {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        } internal static string SelectedCard
        {
            get {
                return ResourceManager.GetString("SelectedCard", resourceCulture);
            }
        } internal static string DeliveryAddress
        {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        internal static string DeliveryZone
        {
            get {
                return ResourceManager.GetString("DeliveryZone", resourceCulture);
            }
        } internal static string Standard
        {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        internal static string minutes
        {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }


        internal static string AdditionalyDelivery
        {
            get {
                return ResourceManager.GetString("AdditionalyDelivery", resourceCulture);
            }
        }
        internal static string ClientBalance
        {
            get {
                return ResourceManager.GetString("ClientBalance", resourceCulture);
            }
        }
        internal static string DeliveryDetail
        {
            get {
                return ResourceManager.GetString("DeliveryDetail", resourceCulture);
            }
        }
        internal static string EnterClientEmail
        {
            get {
                return ResourceManager.GetString("EnterClientEmail", resourceCulture);
            }
        }

        internal static string SalesSum
        {
            get {
                return ResourceManager.GetString("SalesSum", resourceCulture);
            }
        }
        internal static string WriteCommentLabel
        {
            get {
                return ResourceManager.GetString("WriteCommentLabel", resourceCulture);
            }
        }

        internal static string EnterCardNumber
        {
            get {
                return ResourceManager.GetString("EnterCardNumber", resourceCulture);
            }
        } internal static string ChoseLang
        {
            get {
                return ResourceManager.GetString("ChoseLang", resourceCulture);
            }
        } internal static string EnteringSummLessError
        {
            get {
                return ResourceManager.GetString("EnteringSummLessError", resourceCulture);
            }
        }

        internal static string Untie
        {
            get
            {
                return ResourceManager.GetString("Untie", resourceCulture);
            }
        }
        internal static string DisableFiscalReceiptPrinting
        {
            get {
                return ResourceManager.GetString("DisableFiscalReceiptPrinting", resourceCulture);
            }
        }
        internal static string Address
        {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплата.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплата картой.
        /// </summary>
        internal static string PaymentInCard {
            get {
                return ResourceManager.GetString("PaymentInCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплата наличными.
        /// </summary>
        internal static string PaymentInCash {
            get {
                return ResourceManager.GetString("PaymentInCash", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Предыдущие дни.
        /// </summary>
        internal static string PreviousDays {
            get {
                return ResourceManager.GetString("PreviousDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Напечатать чек.
        /// </summary>
        internal static string PrintReceipt {
            get {
                return ResourceManager.GetString("PrintReceipt", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Удален продукт.
        /// </summary>
        internal static string ProductWasRemoved {
            get {
                return ResourceManager.GetString("ProductWasRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Акции.
        /// </summary>
        internal static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Готов.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Чек.
        /// </summary>
        internal static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Архив чеков.
        /// </summary>
        internal static string ReceiptArchive {
            get {
                return ResourceManager.GetString("ReceiptArchive", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь будет отображаться список чеков.
        /// </summary>
        internal static string ReceiptList {
            get {
                return ResourceManager.GetString("ReceiptList", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Чек №.
        /// </summary>
        internal static string ReceiptNumber {
            get {
                return ResourceManager.GetString("ReceiptNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип чека.
        /// </summary>
        internal static string ReceiptType {
            get {
                return ResourceManager.GetString("ReceiptType", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Возврат.
        /// </summary>
        internal static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        internal static string OrderStateLabel
        {
            get {
                return ResourceManager.GetString("OrderStateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Возвраты.
        /// </summary>
        internal static string Refunds {
            get {
                return ResourceManager.GetString("Refunds", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Возвратный.
        /// </summary>
        internal static string Returnable {
            get {
                return ResourceManager.GetString("Returnable", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на РУС.
        /// </summary>
        internal static string Rus {
            get {
                return ResourceManager.GetString("Rus", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Ru.
        /// </summary>
        internal static string RussianLanguage {
            get {
                return ResourceManager.GetString("RussianLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский язык.
        /// </summary>
        internal static string Russion {
            get {
                return ResourceManager.GetString("Russion", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажный.
        /// </summary>
        internal static string Selling {
            get {
                return ResourceManager.GetString("Selling", resourceCulture);
            }
        }

        internal static string WrongPswdError
        {
            get {
                return ResourceManager.GetString("WrongPswdError", resourceCulture);
            }
        }
        internal static string CantCreateCashRegisterError
        {
            get {
                return ResourceManager.GetString("CantCreateCashRegisterError", resourceCulture);
            }
        }
        internal static string Login
        {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        internal static string Pswd
        {
            get {
                return ResourceManager.GetString("Pswd", resourceCulture);
            }
        }
        internal static string FieldRequerd
        {
            get {
                return ResourceManager.GetString("FieldRequerd", resourceCulture);
            }
        }
        internal static string Field
        {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        internal static string BalanceOfMoneyAfterCollection
        {
            get {
                return ResourceManager.GetString("BalanceOfMoneyAfterCollection", resourceCulture);
            }
        } internal static string CantStartCashRegister
        {
            get {
                return ResourceManager.GetString("CantStartCashRegister", resourceCulture);
            }
        }
        internal static string CantEndCashRegister
        {
            get {
                return ResourceManager.GetString("CantEndCashRegister", resourceCulture);
            }
        }
        internal static string EngLang
        {
            get {
                return ResourceManager.GetString("EngLang", resourceCulture);
            }
        }
        internal static string RusLang
        {
            get {
                return ResourceManager.GetString("RusLang", resourceCulture);
            }
        }
        internal static string OzLang
        {
            get {
                return ResourceManager.GetString("OzLang", resourceCulture);
            }
        } internal static string NoFindCashRegister
        {
            get {
                return ResourceManager.GetString("NoFindCashRegister", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.
        /// </summary>
        internal static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }

        internal static string EnterSum
        {
            get {
                return ResourceManager.GetString("EnterSum", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 6.
        /// </summary>
        internal static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Спрайт.
        /// </summary>
        internal static string Sprite {
            get {
                return ResourceManager.GetString("Sprite", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Готовые.
        /// </summary>
        internal static string Succes {
            get {
                return ResourceManager.GetString("Succes", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на №.
        /// </summary>
        internal static string SymbolNumber {
            get {
                return ResourceManager.GetString("SymbolNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Стол.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Стол №.
        /// </summary>
        internal static string TableNumber {
            get {
                return ResourceManager.GetString("TableNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Столы.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на На вынос.
        /// </summary>
        internal static string Takeout {
            get {
                return ResourceManager.GetString("Takeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        internal static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 10000.
        /// </summary>
        internal static string TenThousand {
            get {
                return ResourceManager.GetString("TenThousand", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.
        /// </summary>
        internal static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Отнял количество продукта.
        /// </summary>
        internal static string TookAwayQuantityProduct {
            get {
                return ResourceManager.GetString("TookAwayQuantityProduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на К оплате.
        /// </summary>
        internal static string TotalToPay {
            get {
                return ResourceManager.GetString("TotalToPay", resourceCulture);
            }
        }
        internal static string Prepared
        {
            get {
                return ResourceManager.GetString("Prepared", resourceCulture);
            }
        }
        internal static string OnWayLabel
        {
            get {
                return ResourceManager.GetString("OnWayLabel", resourceCulture);
            }
        }
        internal static string DeliveredLabel
        {
            get {
                return ResourceManager.GetString("DeliveredLabel", resourceCulture);
            }
        }
        internal static string ClosedStatusLabel
        {
            get {
                return ResourceManager.GetString("ClosedStatusLabel", resourceCulture);
            }
        }


        /// <summary>
        ///   Ищет локализованную строку, похожую на 20000.
        /// </summary>
        internal static string TwentyThousand {
            get {
                return ResourceManager.GetString("TwentyThousand", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Типы заказов.
        /// </summary>
        internal static string TypesOfOrders {
            get {
                return ResourceManager.GetString("TypesOfOrders", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на АНГЛ.
        /// </summary>
        internal static string Us {
            get {
                return ResourceManager.GetString("Us", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Узбекский язык.
        /// </summary>
        internal static string Uzbek {
            get {
                return ResourceManager.GetString("Uzbek", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Ждём активации устройства.
        /// </summary>
        internal static string WaitingTheActivationDevice {
            get {
                return ResourceManager.GetString("WaitingTheActivationDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Склад.
        /// </summary>
        internal static string Warehouse2 {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на отменен.
        /// </summary>
        internal static string WasCancelled {
            get {
                return ResourceManager.GetString("WasCancelled", resourceCulture);
            }
        }
        internal static string WasGuestDelete
        {
            get {
                return ResourceManager.GetString("WasGuestDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на был создан.
        /// </summary>
        internal static string WasCreated {
            get {
                return ResourceManager.GetString("WasCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на был удален.
        /// </summary>
        internal static string WasDeleted {
            get {
                return ResourceManager.GetString("WasDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Неделя.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Без оплаты.
        /// </summary>
        internal static string WithoutPayment {
            get {
                return ResourceManager.GetString("WithoutPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на X - отчет.
        /// </summary>
        internal static string Xreport {
            get {
                return ResourceManager.GetString("Xreport", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Z - отчет.
        /// </summary>
        internal static string Zreport {
            get {
                return ResourceManager.GetString("Zreport", resourceCulture);
            }
        }


        internal static string DeliveryLabel
        {
            get {
                return ResourceManager.GetString("DeliveryLabel", resourceCulture);
            }
        }
        internal static string EnterCommentOrder
        {
            get {
                return ResourceManager.GetString("EnterCommentOrder", resourceCulture);
            }
        } internal static string EnterCommentOrderLabel
        {
            get {
                return ResourceManager.GetString("EnterCommentOrderLabel", resourceCulture);
            }
        }
        internal static string TakeAway
        {
            get {
                return ResourceManager.GetString("TakeAway", resourceCulture);
            }
        }

        internal static string EnterTheRemainingCash
        {
            get
            {
                return ResourceManager.GetString("EnterTheRemainingCash", resourceCulture);
            }
        }

        internal static string EnterAComment
        {
            get
            {
                return ResourceManager.GetString("EnterAComment", resourceCulture);
            }
        }

        internal static string DateAndTime
        {
            get
            {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }

        internal static string NumberOfGuests
        {
            get
            {
                return ResourceManager.GetString("NumberOfGuests", resourceCulture);
            }
        }


        internal static string SelectTheNumberOfGuests
        {
            get
            {
                return ResourceManager.GetString("SelectTheNumberOfGuests", resourceCulture);
            }
        }

        internal static string Duration
        {
            get
            {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }

        internal static string SelectDuration
        {
            get
            {
                return ResourceManager.GetString("SelectDuration", resourceCulture);
            }
        }
        
        internal static string CustomerData
        {
            get
            {
                return ResourceManager.GetString("CustomerData", resourceCulture);
            }
        }

        internal static string EnterTheClientName
        {
            get
            {
                return ResourceManager.GetString("EnterTheClientName", resourceCulture);
            }
        }
        internal static string ChooseATable
        {
            get
            {
                return ResourceManager.GetString("ChooseATable", resourceCulture);
            }
        }

        internal static string ToBook
        {
            get
            {
                return ResourceManager.GetString("ToBook", resourceCulture);
            }
        }

        internal static string PlusNewBooking
        {
            get
            {
                return ResourceManager.GetString("PlusNewBooking", resourceCulture);
            }
        }

        internal static string CustomerNameAndNumber
        {
            get
            {
                return ResourceManager.GetString("CustomerNameAndNumber", resourceCulture);
            }
        }

        internal static string CreatingATransaction
        {
            get
            {
                return ResourceManager.GetString("CreatingATransaction", resourceCulture);
            }
        }

        internal static string Expenditure
        {
            get
            {
                return ResourceManager.GetString("Expenditure", resourceCulture);
            }
        }


        internal static string Introduction
        {
            get
            {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }

        internal static string Collection
        {
            get
            {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }

        internal static string EnterTheTransactionAmount
        {
            get
            {
                return ResourceManager.GetString("EnterTheTransactionAmount", resourceCulture);
            }
        }



        internal static string SelectTheType
        {
            get
            {
                return ResourceManager.GetString("SelectTheType", resourceCulture);
            }
        }


        internal static string TheDateOfTheAgreementIsDifferent
        {
            get
            {
                return ResourceManager.GetString("TheDateOfTheAgreementIsDifferent", resourceCulture);
            }
        }

        internal static string ToCreate
        {
            get
            {
                return ResourceManager.GetString("ToCreate", resourceCulture);
            }
        }


       internal static string RegisteringAWiFiPrinter
        {
            get
            {
                return ResourceManager.GetString("RegisteringAWiFiPrinter", resourceCulture);
            }
        }


        internal static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        internal static string EnterTheIpAddress
        {
            get
            {
                return ResourceManager.GetString("EnterTheIpAddress", resourceCulture);
            }
        }

        internal static string ShiftManagement
        {
            get
            {
                return ResourceManager.GetString("ShiftManagement", resourceCulture);
            }
        }

        internal static string Notifications
        {
            get
            {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }

        internal static string TheOrderWasReturned
        {
            get
            {
                return ResourceManager.GetString("TheOrderWasReturned", resourceCulture);
            }
        }


        internal static string SentForPrintingToThePrinter
        {
            get
            {
                return ResourceManager.GetString("SentForPrintingToThePrinter", resourceCulture);
            }
        }

        internal static string TotalAmountToBePaid
        {
            get
            {
                return ResourceManager.GetString("TotalAmountToBePaid", resourceCulture);
            }
        }


        internal static string Cashier
        {
            get
            {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }


        internal static string Printed
        {
            get
            {
                return ResourceManager.GetString("Printed", resourceCulture);
            }
        }


        internal static string TheOrderIsOpen
        {
            get
            {
                return ResourceManager.GetString("TheOrderIsOpen", resourceCulture);
            }
        }


        internal static string ErrorWhenAuthorizingTheDevice
        {
            get
            {
                return ResourceManager.GetString("ErrorWhenAuthorizingTheDevice", resourceCulture);
            }
        }


        internal static string Kz
        {
            get
            {
                return ResourceManager.GetString("Kz", resourceCulture);
            }
        }


        internal static string TheEstimatedAmountInTheCashRegisterDoesNotMatch
        {
            get
            {
                return ResourceManager.GetString("TheEstimatedAmountInTheCashRegisterDoesNotMatch", resourceCulture);
            }
        }


        internal static string MistakeTheBalance
        {
            get
            {
                return ResourceManager.GetString("MistakeTheBalance", resourceCulture);
            }
        }


        internal static string MistakeIsImpossibleToClose
        {
            get
            {
                return ResourceManager.GetString("MistakeIsImpossibleToClose", resourceCulture);
            }
        }

        internal static string TheBeginningShift
        {
            get
            {
                return ResourceManager.GetString("TheBeginningShift", resourceCulture);
            }
        }


        internal static string TypesOfPayment
        {
            get
            {
                return ResourceManager.GetString("TypesOfPayment", resourceCulture);
            }
        }


        internal static string CashlessPayment
        {
            get
            {
                return ResourceManager.GetString("CashlessPayment", resourceCulture);
            }
        }

        internal static string CashPayment
        {
            get
            {
                return ResourceManager.GetString("CashPayment", resourceCulture);
            }
        }


        internal static string ResultsOfOperations
        {
            get
            {
                return ResourceManager.GetString("ResultsOfOperations", resourceCulture);
            }
        }

        internal static string Sales
        {
            get
            {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }

        internal static string TotalDocuments
        {
            get
            {
                return ResourceManager.GetString("TotalDocuments", resourceCulture);
            }
        }

        internal static string Corrupt
        {
            get
            {
                return ResourceManager.GetString("Corrupt", resourceCulture);
            }
        }

        internal static string CashOnHand
        {
            get
            {
                return ResourceManager.GetString("CashOnHand", resourceCulture);
            }
        }


        internal static string ChangeableTotal
        {
            get
            {
                return ResourceManager.GetString("ChangeableTotal", resourceCulture);
            }
        }

        internal static string TheReportWasDevice
        {
            get
            {
                return ResourceManager.GetString("TheReportWasDevice", resourceCulture);
            }
        }

        internal static string ShiftReport
        {
            get
            {
                return ResourceManager.GetString("ShiftReport", resourceCulture);
            }
        }

        

        internal static string YouDontWorkTerminal
        {
            
            get
            {
                return ResourceManager.GetString("YouDontWorkTerminal", resourceCulture);
            }
        }

        internal static string FailedLogin
        {
            
            get
            {
                return ResourceManager.GetString("FailedLogin", resourceCulture);
            }
        }

        internal static string NotFound
        {

            get
            {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }

        internal static string entrance
        {
            get
            {
                return ResourceManager.GetString("entrance", resourceCulture);
            }
        }

        internal static string OrderIsPaid
        {
            get
            {
                return ResourceManager.GetString("OrderIsPaid", resourceCulture);
            }
        }
    }


}
